### ISSUE TITLE
Appstream file missing developer_name

### ISSUE THREAD

**Issue by TingPing** [flathub/org.opencpn.OpenCPN#31]
This has become a requirement on Flathub so this fails to build.

**Comment by leamas** [comment]
hm... Is a deprecated tag mandatory? https://freedesktop.org/software/appstream/docs/chap-Metadata.html.  Use `<developer>` instead?

**Comment by leamas** [comment]
@TingPing ^

**Comment by TingPing** [comment]
Yes the old name is required. Flathub's infrastructure uses an older library for appstream data.

**Comment by leamas** [comment]
Resolved, closing
